services:
  postgres:
    image: postgres:alpine
    command: postgres -N 500
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  elasticsearch:
    image: elasticsearch:8.6.2
    restart: always
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      mem_limit: 1024m
      xpack.security.enabled: false
      discovery.type: single-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  redis:
    image: redis/redis-stack:latest
    restart: always
    volumes:
      - redis_data:/data
      - ./priv/repo/dump.rdb:/data/dump.rdb
    ports:
      - 6379:6379
      - 8001:8001
volumes:
  postgres_data:
  elasticsearch_data:
  redis_data:
