services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  elasticsearch:
    image: elasticsearch:8.6.2
    restart: always
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  postgres_data:
  elasticsearch_data:
