name: ESLint

on:
  push:
    branches: [main]
    paths: [ "apps/frontend/**", ".github/workflows/lint-frontend.yaml" ]
  pull_request:
    branches: [main]
    paths: [ "apps/frontend/**", ".github/workflows/lint-frontend.yaml" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - uses: actions/checkout@v3
      # - run: echo "::add-matcher::.github/annotation-eslint.json"
      - run: echo "::add-matcher::.github/annotation-typescript.json"
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: apps/frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: TypeScript
        run: ./node_modules/.bin/tsc --noEmit
        continue-on-error: true

      # - name: ESLint
      #   run: ./node_modules/.bin/eslint -f stylish
      #   continue-on-error: true