name: ESLint

on:
  push:
    branches: [main]
    paths: [ "apps/frontend/**", ".github/workflows/lint-frontend.yaml" ]
  pull_request:
    branches: [main]
    paths: [ "apps/frontend/**", ".github/workflows/lint-frontend.yaml" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: read
    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: apps/frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: ESLint
        run: ./node_modules/.bin/eslint -f json --output-file report-eslint.json
        continue-on-error: true

      - name: Type check
        run: ./node_modules/.bin/tsc --noEmit > report-typescript.log
        continue-on-error: true

      - name: Annotate issues
        uses: DerLev/eslint-annotations@v2
        with:
          only-changed-in-pr: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          eslint-report: apps/frontend/report-eslint.json
          typescript-log: apps/frontend/report-typescript.log